// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBelBaFqVhVvhQNcSKulOGc2n-gOfB7a9g',
    appId: '1:587164217387:web:67ac24ed2ae86e078eba6e',
    messagingSenderId: '587164217387',
    projectId: 'form-registration-63e0a',
    authDomain: 'form-registration-63e0a.firebaseapp.com',
    storageBucket: 'form-registration-63e0a.appspot.com',
    measurementId: 'G-ZR7K50SRFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBND8kz0v0D03U8V49_ey9xrj6K5WNijgU',
    appId: '1:587164217387:android:49e8e5cb42a3eb9a8eba6e',
    messagingSenderId: '587164217387',
    projectId: 'form-registration-63e0a',
    storageBucket: 'form-registration-63e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwIQpA2zZdXnhW5KfdfFxPBDzzzkDeg0',
    appId: '1:587164217387:ios:05cc412c881d683c8eba6e',
    messagingSenderId: '587164217387',
    projectId: 'form-registration-63e0a',
    storageBucket: 'form-registration-63e0a.appspot.com',
    iosBundleId: 'com.example.formApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwIQpA2zZdXnhW5KfdfFxPBDzzzkDeg0',
    appId: '1:587164217387:ios:7e6d7cefa09a8b958eba6e',
    messagingSenderId: '587164217387',
    projectId: 'form-registration-63e0a',
    storageBucket: 'form-registration-63e0a.appspot.com',
    iosBundleId: 'com.example.formApp.RunnerTests',
  );
}
